[font]
size=14.0

[font.bold]
family = "firacodeNerdFont"
style = "Bold"

[font.bold_italic]
family = "firacodeNerdFont"
style = "Bold Italic"

[font.italic]
family = "firacodeNerdFont"
style = "Italic"

[font.normal]
family = "firacodeNerdFont"
style = "Regular"

[window]
opacity=0.6
